## this is a not polished version of the flow, just to test the COPY method 
##for data ingestion into PostgreSQL. The flow will be refactored and optimized in the next iterations.


id: python-postgres-ingestion_COPY_method_v5
namespace: company.team
description: Scheduled flow to ingest data into PostgreSQL using a Python script.

inputs:
  - id: year
    type: SELECT
    displayName: "Year"
    defaults: "2026"
    values:
      - "2020"
      - "2021"
      - "2022"
      - "2023"
      - "2024"
      - "2025"
      - "2026"

  - id: month
    type: SELECT
    defaults: "01"
    displayName: "Month"
    values:
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"

  - id: taxi_type
    type: SELECT
    defaults: "green"
    displayName: "Taxi Type"
    values:
      - green
      - yellow

triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"

tasks:
  - id: which_taxi_type
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.taxi_type == 'green' }}"
    then:
      - id: if_green
        type: io.kestra.plugin.core.log.Log
        message: "green taxi data ingested"


      - id: ingest_data_python_green_data
        type: io.kestra.plugin.scripts.python.Script
        description: Run a Python script to ingest data into PostgreSQL.
        containerImage: ing_dependencies:latest
    
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: IF_NOT_PRESENT
          networkMode: nyc_taxi_local_setup_default
          cpu:
            cpus: 1
          memory:
            memory: "2Gb"
    
        script: |
          import pandas as pd
          import io
          import psycopg2
          from tqdm import tqdm

          year = "{{ inputs.year }}"
          month = "{{ inputs.month }}"
          taxi_type = "{{ inputs.taxi_type }}"
    
          username = "{{ kv('username') }}"
          password = "{{ kv('password') }}"
    
          conn = psycopg2.connect(
              host="postgres",   # or "postgres" in docker
              database="NYC_Taxi",
              user= username,
              password= password
          )
          cursor = conn.cursor()
    
          def load_taxi_data(year, month, taxi_type):
              prefix = "https://d37ci6vzurychx.cloudfront.net/trip-data/"
              month = str(month).zfill(2)
              url = f"{prefix}{taxi_type}_tripdata_{year}-{month}.parquet"
              df = pd.read_parquet(url, engine="pyarrow")
              table_name = f"{taxi_type}_tripdata_{year}_{month}"
              return df, table_name
              
          df,table_name = load_taxi_data(year,month,taxi_type)
          buffer = io.StringIO()
          df.to_csv(buffer, index=False, header=False)
          buffer.seek(0)
          
          cursor.execute(f"""
          DROP TABLE IF EXISTS public.{table_name};
          CREATE TABLE  public.{table_name} (
            "VendorID" integer,
            lpep_pickup_datetime timestamp without time zone,
            lpep_dropoff_datetime timestamp without time zone,
            store_and_fwd_flag text COLLATE pg_catalog."default",
            "RatecodeID" double precision,
            "PULocationID" integer,
            "DOLocationID" integer,
            passenger_count double precision,
            trip_distance double precision,
            fare_amount double precision,
            extra double precision,
            mta_tax double precision,
            tip_amount double precision,
            tolls_amount double precision,
            ehail_fee double precision,
            improvement_surcharge double precision,
            total_amount double precision,
            payment_type double precision,
            trip_type double precision,
            congestion_surcharge double precision,
            cbd_congestion_fee double precision
          );    
          """)
          conn.commit()
          cursor.copy_expert(
              f"COPY {table_name} FROM STDIN WITH CSV",
              buffer
          )
          conn.commit()
          cursor.close()
          conn.close()
      - id: create_green_table
        type: io.kestra.plugin.jdbc.postgresql.Query
        url: jdbc:postgresql://postgres:5432/NYC_Taxi
        username: "{{ kv('username') }}"
        password: "{{ kv('password') }}"
        sql: |
          CREATE TABLE IF NOT EXISTS public.raw_{{ inputs.taxi_type }}_tripdata (
              trip_id VARCHAR PRIMARY KEY,
              "VendorID" integer,
              lpep_pickup_datetime timestamp,
              lpep_dropoff_datetime timestamp,
              store_and_fwd_flag text,
              "RatecodeID" double precision,
              "PULocationID" integer,
              "DOLocationID" integer,
              passenger_count double precision,
              trip_distance double precision,
              fare_amount double precision,
              extra double precision,
              mta_tax double precision,
              tip_amount double precision,
              tolls_amount double precision,
              ehail_fee double precision,
              improvement_surcharge double precision,
              total_amount double precision,
              payment_type double precision,
              trip_type double precision,
              congestion_surcharge double precision,
              cbd_congestion_fee double precision,
              file_name VARCHAR,
              ingestion_datetime timestamp,
              updated_datetime timestamp
          );
      - id: upsert_green_data
        type: io.kestra.plugin.jdbc.postgresql.Query
        url: jdbc:postgresql://postgres:5432/NYC_Taxi
        username: "{{ kv('username') }}"
        password: "{{ kv('password') }}"
        sql: |
          INSERT INTO public.raw_{{inputs.taxi_type}}_tripdata (
              trip_id,
              "VendorID",
              lpep_pickup_datetime,
              lpep_dropoff_datetime,
              store_and_fwd_flag,
              "RatecodeID",
              "PULocationID",
              "DOLocationID",
              passenger_count,
              trip_distance,
              fare_amount,
              extra,
              mta_tax,
              tip_amount,
              tolls_amount,
              ehail_fee,
              improvement_surcharge,
              total_amount,
              payment_type,
              trip_type,
              congestion_surcharge,
              cbd_congestion_fee,
              file_name,
              ingestion_datetime,
              updated_datetime
          )
          SELECT
              MD5(
                  concat_ws(
                      '||',
                      coalesce("VendorID"::text, ''),
                      coalesce(lpep_pickup_datetime::text, ''),
                      coalesce(lpep_dropoff_datetime::text, ''),
                      coalesce("PULocationID"::text, ''),
                      coalesce("DOLocationID"::text, ''),
                      coalesce(trip_distance::text, ''),
                      coalesce(fare_amount::text, ''),
                      coalesce(total_amount::text, ''),
                      coalesce(passenger_count::text, '')
                  )
              ) AS trip_id,
              "VendorID",
              lpep_pickup_datetime,
              lpep_dropoff_datetime,
              store_and_fwd_flag,
              "RatecodeID",
              "PULocationID",
              "DOLocationID",
              passenger_count,
              trip_distance,
              fare_amount,
              extra,
              mta_tax,
              tip_amount,
              tolls_amount,
              ehail_fee,
              improvement_surcharge,
              total_amount,
              payment_type,
              trip_type,
              congestion_surcharge,
              cbd_congestion_fee,
              '{{ inputs.taxi_type }}_tripdata_{{ inputs.year }}_{{ inputs.month }}' AS file_name,
              NOW(),
              NULL
          FROM {{ inputs.taxi_type }}_tripdata_{{ inputs.year }}_{{ inputs.month }}
          ON CONFLICT (trip_id)
          DO UPDATE SET
              "VendorID" = excluded."VendorID",
              lpep_pickup_datetime = excluded.lpep_pickup_datetime,
              lpep_dropoff_datetime = excluded.lpep_dropoff_datetime,
              store_and_fwd_flag = excluded.store_and_fwd_flag,
              "RatecodeID" = excluded."RatecodeID",
              "PULocationID" = excluded."PULocationID",
              "DOLocationID" = excluded."DOLocationID",
              passenger_count = excluded.passenger_count,
              trip_distance = excluded.trip_distance,
              fare_amount = excluded.fare_amount,
              extra = excluded.extra,
              mta_tax = excluded.mta_tax,
              tip_amount = excluded.tip_amount,
              tolls_amount = excluded.tolls_amount,
              ehail_fee = excluded.ehail_fee,
              improvement_surcharge = excluded.improvement_surcharge,
              total_amount = excluded.total_amount,
              payment_type = excluded.payment_type,
              trip_type = excluded.trip_type,
              congestion_surcharge = excluded.congestion_surcharge,
              cbd_congestion_fee = excluded.cbd_congestion_fee,
              file_name = excluded.file_name,
              ingestion_datetime = excluded.ingestion_datetime,
              updated_datetime = NOW();

    else:
      - id: if_yellow
        type: io.kestra.plugin.core.log.Log
        message: "yellow data ingestion"
      - id: ingest_data_python_yellow_data
        type: io.kestra.plugin.scripts.python.Script
        description: Run a Python script to ingest data into PostgreSQL.
        containerImage: ing_dependencies:latest
    
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: IF_NOT_PRESENT
          networkMode: nyc_taxi_local_setup_default
          cpu:
            cpus: 3
          memory:
            memory: "4Gb"
    
        script: |
                  import pandas as pd
                  import io
                  import psycopg2
                  from tqdm import tqdm

                  year = "{{ inputs.year }}"
                  month = "{{ inputs.month }}"
                  taxi_type = "{{ inputs.taxi_type }}"

                  username = "{{ kv('username') }}"
                  password = "{{ kv('password') }}"

                  conn = psycopg2.connect(
                      host="postgres",   # or "postgres" in docker
                      database="NYC_Taxi",
                      user= username,
                      password= password
                  )
                  cursor = conn.cursor()

                  def load_taxi_data(year, month, taxi_type):
                      prefix = "https://d37ci6vzurychx.cloudfront.net/trip-data/"
                      month = str(month).zfill(2)
                      url = f"{prefix}{taxi_type}_tripdata_{year}-{month}.parquet"
                      df = pd.read_parquet(url, engine="pyarrow")
                      table_name = f"{taxi_type}_tripdata_{year}_{month}"
                      return df, table_name

                  df,table_name = load_taxi_data(year,month,taxi_type)
                  buffer = io.StringIO()
                  df.to_csv(buffer, index=False, header=False)
                  buffer.seek(0)

                  cursor.execute(f"""
                  DROP TABLE IF EXISTS public.{table_name};
                  CREATE TABLE  public.{table_name} (
                      "VendorID" integer,
                      tpep_pickup_datetime timestamp without time zone,
                      tpep_dropoff_datetime timestamp without time zone,
                      passenger_count double precision,
                      trip_distance double precision,
                      "RatecodeID" double precision,
                      store_and_fwd_flag text COLLATE pg_catalog."default",
                      "PULocationID" integer,
                      "DOLocationID" integer,
                      payment_type bigint,
                      fare_amount double precision,
                      extra double precision,
                      mta_tax double precision,
                      tip_amount double precision,
                      tolls_amount double precision,
                      improvement_surcharge double precision,
                      total_amount double precision,
                      congestion_surcharge double precision,
                      "Airport_fee" double precision,
                      cbd_congestion_fee double precision
                    );      
                  """)              
                  conn.commit()
                  cursor.copy_expert(
                      f"COPY {table_name} FROM STDIN WITH CSV",
                      buffer
                  )

                  conn.commit()
                  cursor.close()
                  conn.close()
      - id: create_yellow_table
        type: io.kestra.plugin.jdbc.postgresql.Query
        url: jdbc:postgresql://postgres:5432/NYC_Taxi
        username: "{{ kv('username') }}"
        password: "{{ kv('password') }}"
        sql: |
          CREATE TABLE IF NOT EXISTS public.raw_{{ inputs.taxi_type }}_tripdata (
              trip_id VARCHAR PRIMARY KEY,
              "VendorID" integer,
              tpep_pickup_datetime timestamp without time zone,
              tpep_dropoff_datetime timestamp without time zone,
              passenger_count double precision,
              trip_distance double precision,
              "RatecodeID" double precision,
              store_and_fwd_flag text COLLATE pg_catalog."default",
              "PULocationID" integer,
              "DOLocationID" integer,
              payment_type bigint,
              fare_amount double precision,
              extra double precision,
              mta_tax double precision,
              tip_amount double precision,
              tolls_amount double precision,
              improvement_surcharge double precision,
              total_amount double precision,
              congestion_surcharge double precision,
              "Airport_fee" double precision,
              cbd_congestion_fee double precision,
              file_name VARCHAR,
              ingestion_datetime timestamp,
              updated_datetime timestamp
          );
    
      - id: upsert_yellow_data
        type: io.kestra.plugin.jdbc.postgresql.Query
        url: jdbc:postgresql://postgres:5432/NYC_Taxi
        username: "{{ kv('username') }}"
        password: "{{ kv('password') }}"
        sql: |
          INSERT INTO public.raw_{{ inputs.taxi_type }}_tripdata (
              trip_id,
              "VendorID",
              tpep_pickup_datetime ,
              tpep_dropoff_datetime ,
              passenger_count ,
              trip_distance ,
              "RatecodeID" ,
              store_and_fwd_flag,
              "PULocationID" ,
              "DOLocationID" ,
              payment_type ,
              fare_amount ,
              extra ,
              mta_tax ,
              tip_amount ,
              tolls_amount ,
              improvement_surcharge ,
              total_amount,
              congestion_surcharge,
              "Airport_fee",
              cbd_congestion_fee,
              file_name,
              ingestion_datetime,
              updated_datetime
          )
          SELECT
              MD5(
                  concat_ws(
                      '||',
                      coalesce("VendorID"::text, ''),
                      coalesce(tpep_pickup_datetime::text, ''),
                      coalesce(tpep_dropoff_datetime::text, ''),
                      coalesce("PULocationID"::text, ''),
                      coalesce("DOLocationID"::text, ''),
                      coalesce(trip_distance::text, ''),
                      coalesce(fare_amount::text, ''),
                      coalesce(total_amount::text, ''),
                      coalesce(passenger_count::text, '')
                  )
              ) AS trip_id,
              "VendorID",
              tpep_pickup_datetime ,
              tpep_dropoff_datetime ,
              passenger_count ,
              trip_distance ,
              "RatecodeID" ,
              store_and_fwd_flag,
              "PULocationID" ,
              "DOLocationID" ,
              payment_type ,
              fare_amount ,
              extra ,
              mta_tax ,
              tip_amount ,
              tolls_amount ,
              improvement_surcharge ,
              total_amount,
              congestion_surcharge,
              "Airport_fee",
              cbd_congestion_fee, 
              '{{ inputs.taxi_type }}_tripdata_{{ inputs.year }}_{{ inputs.month }}' AS file_name,
              NOW(),
              NULL
          FROM {{ inputs.taxi_type }}_tripdata_{{ inputs.year }}_{{ inputs.month }}
          ON CONFLICT (trip_id)
          DO UPDATE SET
              "VendorID" = excluded."VendorID",
              tpep_pickup_datetime = excluded.tpep_pickup_datetime,
              tpep_dropoff_datetime = excluded.tpep_dropoff_datetime,
              store_and_fwd_flag = excluded.store_and_fwd_flag,
              "RatecodeID" = excluded."RatecodeID",
              "PULocationID" = excluded."PULocationID",
              "DOLocationID" = excluded."DOLocationID",
              passenger_count = excluded.passenger_count,
              trip_distance = excluded.trip_distance,
              fare_amount = excluded.fare_amount,
              extra = excluded.extra,
              mta_tax = excluded.mta_tax,
              tip_amount = excluded.tip_amount,
              tolls_amount = excluded.tolls_amount,
              improvement_surcharge = excluded.improvement_surcharge,
              total_amount = excluded.total_amount,
              payment_type = excluded.payment_type,
              congestion_surcharge = excluded.congestion_surcharge,
              cbd_congestion_fee = excluded.cbd_congestion_fee,
              file_name = excluded.file_name,
              ingestion_datetime = excluded.ingestion_datetime,
              updated_datetime = NOW();

      